### ISSUE TITLE
where is the two text file on this coding

### ISSUE THREAD

**Issue by moorthysmart** [tomassykora/retina-optic-disc-detector#1]
if args.train is True:
		detector.train('.images/train/', '.images/gt_train.txt')
	elif args.finetune is True:
		detector.fine_tune('./images/train/', './images/gt_train.txt')
	elif args.detect is True:
		detector.detect('./test_image.png')
	elif args.eval is True:
		detector.eval_model('./images', './images/imageret_gt.txt')
	else:
		print('No argument set.')

imageret_gt.txt ,gt_train.txt where is the two value ??? of text doc is missing or ?

**Comment by tomassykora** [comment]
Hi @moorthysmart, 

the text files are not included in the repository. They're the ground truth data and are available on the official STARE database page. For the imageret database I'm not sure whether they're also available on their page, try and check it. 

Also be sure that the gt data are in appropriate format according to image sizes, as the original images from the database are in high resolution and I'm resizing them, so the gt data must fit to them too. 

I'll probably rework the whole code in the near future to make it more clear, because it's a mess now :-)

**Comment by moorthysmart** [comment]
please help me sir . i have this project code but its not run on my system ubuntu python 2.7 .please help me sir

**Comment by moorthysmart** [comment]
detector.train('.images/train/', '.images/gt_train.txt')
detector.fine_tune('./images/train/', './images/gt_train.txt')
detector.eval_model('./images', './images/imageret_gt.txt')
please sir/madam  i cannot find the file sir. please help me out .. i have project on image processing please help me to find me the solution ..

**Comment by ronnyshalev** [comment]
Hello,

I downloaded the ground truth table fro the Messidor website. It comes in the format as follows:
im0001.jpg 266 65
im0002.jpg 273 91
im0003.jpg 262 56
...
However the function crashes when it tries to read the file and I was wondering if you are willing to share the format of your file.

Ronny

**Comment by tomassykora** [comment]
Hello @ronnyshalev 

I don't really remember what the format of the ground truth was (I can probably check it later this week), but from what I see in the code, there seems to be a typo on the line 673, there is a mising '/' in the path (it should be './images/train/'). I'm not sure if this is the problem here as I cannot try it myself for now, but try it and let me know. If it is not the problem, I'll try to check it later.

Tomas

**Comment by ronnyshalev** [comment]
Thank you very much for your reply. I would greatly appreciate it if you could check.
The typo you mention was not the problem (I saw it when I started). The program fails on line 277 (train_output = np.loadtxt(gt_file)). I am not sure why, but I am getting the error: "ValueError: could not convert string to float: 'im0001.jpg'" where im0001.jpg is the first value in the gt_file text file.

It may have to do with the operating system (I am using Windows 10), but I could not find anything wrong with the code, so I am assuming the gt_file is the source of the problem.

**Comment by tomassykora** [comment]
It shouldn't be caused by win 10, I used it also. I will check that and give you an update.

**Comment by ronnyshalev** [comment]
Thank you !!

**Comment by ronnyshalev** [comment]
@tomassykora
I was wondering if you had a chance to check the file format.

Thanks
Ronny
